# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.cache/wt} [current_project]
set_property parent.project_path {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_files/Ready_Modules/SevSeg_4digit.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/idle_detector_4bit.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_files/Ready_Modules/keypad4X4.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/mapper_module.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/movement_memory.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/negedge_detector.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/posedge_detector.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/rng_4bit.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/seven_segment_logic.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/signal_delayer_1bit.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_files/Ready_Modules/stepmotor.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_files/Ready_Modules/steppermotor_wrapper.sv}
  {D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/sources_1/new/game.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{D:/Documents/Bilkent/Year 2 Semester 1/CS223/Project/Project_Vivado/CS223_Project.srcs/constrs_1/new/constraints.xdc}}]


synth_design -top game -part xc7a35tcpg236-1


write_checkpoint -force -noxdef game.dcp

catch { report_utilization -file game_utilization_synth.rpt -pb game_utilization_synth.pb }
